version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test

  db:
    image: postgis/postgis:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres", "-d", "postgres", "-w", "postgres" ]
      interval: 5s
      timeout: 10s
      retries: 30
    networks:
      - test

networks:
  test:
