POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "p@ssw0rd",
  "username": "TesterUsername"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "p@ssw0rd"
}

###

POST http://localhost:8080/auth/logout
Content-Type: application/json

{
  "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUZXN0ZXJVc2VybmFtZSIsImlhdCI6MTY3Nzc1NjI1OSwiZXhwIjoxNjc3NzU3MTU5fQ.nfM40-3WBBaevZZInhCKtnGz_JjfesrpogFuqrXnOHU"
}

###

GET http://localhost:8080/auth/me
Accept: application/json

###