POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "p@ssw0rd",
  "username": "TesterUsername"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "p@ssw0rd"
}

###

POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{}

###

GET http://localhost:8080/api/auth/me
Accept: application/json

###