POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "p@ssw0rd",
  "username": "TesterUsername"
}

###

POST http://localhost:8080/auth/forgot-password
Content-Type: application/json

{
  "email": "user@example.com"
}

###

POST http://localhost:8080/auth/reset-password
Content-Type: application/json

{
  "token": "390b5aee-543c-4e3c-8333-42646267268e",
  "newPassword": "NewTestPassword123"
}

###

