POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "p@ssw0rd",
  "username": "TesterUsername"
}

###

POST http://localhost:8080/user-action/new
Content-Type: application/json

{
  "user": {
    "id": "1"
  },
  "newValue": "testing value",
  "url": "/testurl/something",
  "action": "REMOVED_VALUE",
  "componentType": "INPUT"
}

###

POST http://localhost:8080/user-action/new
Content-Type: application/json

{
  "user": {
    "id": "1"
  },
  "newValue": false,
  "url": "/testurl/something",
  "action": "CHANGED_VALUE",
  "componentType": "INPUT"
}

###

POST http://localhost:8080/user-action/new
Content-Type: application/json

{
  "user": {
    "id": "1"
  },
  "newValue": 2,
  "url": "/testurl/something",
  "action": "ADDED_VALUE",
  "componentType": "BUTTON"
}

###

POST http://localhost:8080/user-action/new
Content-Type: application/json

{
  "user": {
    "id": "1"
  },
  "newValue": null,
  "url": "/testurl/something",
  "action": "SCROLL",
  "componentType": null
}

###

POST http://localhost:8080/user-action/new
Content-Type: application/json

{
  "user": {
    "id": "1"
  },
  "newValue": "asdf",
  "url": "/testurl/something",
  "action": "SCROLL",
  "componentType": null
}

###

POST http://localhost:8080/user-action/new
Content-Type: application/json

{
  "user": {
    "id": "1"
  },
  "newValue": null,
  "url": "/testurl/something",
  "action": "SCROLL",
  "componentType": "BUTTON"
}

###

POST http://localhost:8080/user-action/new
Content-Type: application/json

{
  "user": {
    "id": "1"
  },
  "newValue": "new test value",
  "url": "/testurl/something",
  "action": "CLICK",
  "componentType": "LINK"
}

###
GET http://localhost:8080/user-action/get
Accept: application/json

###
